### ISSUE TITLE
Bot being flagged 

### ISSUE THREAD

**Issue by ImBubble1** [17teen/Discord-Mass-DM-Tool#14]
I used the bot on a 260 member server, bot kept getting flagged after 20-40 dms (using the 9 and 3 second delay)

**Comment by 17teen** [comment]
How many attempts?

**Comment by ImBubble1** [comment]
up to now i'd say I've done 10ish (applications on different accs aswell)

**Comment by 17teen** [comment]
Bot flagging is expected.
