### ISSUE TITLE
Being able to use a normal user token

### ISSUE THREAD

**Issue by FloFlan** [17teen/Discord-Mass-DM-Tool#16]
Since you need your bot to be in the server you wanna DM the members, it could be cool to have a feature where you can use a user token to DM members of a server you don't own / can add the bot to.

**Comment by 17teen** [comment]
Using a user client would be essentially useless. An account would be rate limited and discord would lock you out of the account after seconds of mass dming.

I don't care if you are planning to use it on a alt. It would be a waste of your time. I don't condone Mass DM advertisement as it's against ToS
