### ISSUE TITLE
DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by CPTRS777** [17teen/Discord-Mass-DM-Tool#5]
"Fetching Guild Error: DiscordAPIError: Missing Access"

Receiving this error code.  Both bot intents are enabled with Admin privileges.  

Any advice?

**Comment by 17teen** [comment]
If the bot is not in the server at the time you have ran the script it will say ""Fetching Guild Error: DiscordAPIError: Missing Access"

"
