### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by nmnsharma007** [17teen/Discord-Mass-DM-Tool#6]
My defender says its a virus though i think its not just tell me if it is

**Comment by msesjrl** [comment]
If you're not sure whether it's a virus or not, you shouldn't be using these tools. It isn't a virus but actually learn coding not just run scripts from GitHub

**Comment by 17teen** [comment]
Tell your shitty defender to give proof as to why this is a virus. How it works and it's origin.
