### ISSUE TITLE
Doesn't send complete message

### ISSUE THREAD

**Issue by IlangoGames** [17teen/Discord-Mass-DM-Tool#9]
For ex I want it to DM
Heyyy xx 

This server has a bunch of leaks, including belle delphines nudes posted! All for free!! 
..
If you want my nudes you should go to ..
If you just want to talk in a nice server go to ..<3

**Comment by IlangoGames** [comment]
It would only say 
"Heyyy xx" 

instead of all that comes after

**Comment by msesjrl** [comment]
Wtf is this

**Comment by IlangoGames** [comment]
dont even ask

**Comment by xmW1** [comment]
> dont even ask

LMAOO wsg

**Comment by dhruvadeep** [comment]
> dont even ask

Looks sketchy. 😂
Try to look at script.js

**Comment by 17teen** [comment]
To lay out the message in the way you want it you must escape sequences. i.e `\n`, `\t`, `\\` etc.

Write it like this:
```
Heyyy xx\n\nThis server has a bunch of leaks, including belle delphines nudes posted! All for free!!\nIf you want my nudes you should go to ..\nIf you just want to talk in a nice server go to ..<3
```

**Comment by BrokenKaneki** [comment]
> To lay out the message in the way you want it you must use escape sequences. i.e `\n`, `\t`, `\\` etc.
> 
> Write it like this:
> 
> ```
> Heyyy xx\n\nThis server has a bunch of leaks, including belle delphines nudes posted! All for free!!\nIf you want my nudes you should go to ..\nIf you just want to talk in a nice server go to ..<3
> ```

ohhh makes sense. tysm

**Comment by IlangoGames** [comment]
> To lay out the message in the way you want it you must use escape sequences. i.e `\n`, `\t`, `\\` etc.
> 
> Write it like this:
> 
> ```
> Heyyy xx\n\nThis server has a bunch of leaks, including belle delphines nudes posted! All for free!!\nIf you want my nudes you should go to ..\nIf you just want to talk in a nice server go to ..<3
> ```

I believe I messed something up since it appears like this now https://prnt.sc/17ga19u

**Comment by 17teen** [comment]
> > To lay out the message in the way you want it you must use escape sequences. i.e `\n`, `\t`, `\\` etc.
> > Write it like this:
> > ```
> > Heyyy xx\n\nThis server has a bunch of leaks, including belle delphines nudes posted! All for free!!\nIf you want my nudes you should go to ..\nIf you just want to talk in a nice server go to ..<3
> > ```
> 
> I believe I messed something up since it appears like this now https://prnt.sc/17ga19u

I cannot see any screenshots from that URL.

**Comment by IlangoGames** [comment]
![image](https://user-images.githubusercontent.com/35138280/124369023-b026b100-dc67-11eb-86bf-044ec4612639.png)

**Comment by IlangoGames** [comment]
Instead of creating a new line it just sends it like that

**Comment by 17teen** [comment]
The tool has been updated. You can now use escape sequences. i.e `\n,` `\t`, `\\` etc. in `settings.json`. Look at the README for the further guidance
